name: Validate Claims
on:
  workflow_dispatch:
  push: { branches: [ main ] }
  pull_request:
jobs:
  run-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python cli_validator.py --doc sample/test.docx --claims sample/claims.json --out results.csv
      - uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: results.csv
